sudo: required

language: php

services: 
  - docker

before_install:
  - docker build -t jianzhong/php7_fpm_symfony4_git -f docker/fpm.Dockerfile
  
script:
  - docker container run --rm -v $(pwd):/var/www/app jianzhong/php7_fpm_symfony4_git:latest bin/phpunit