version: '3.7'
services:
  web:
    image: nginx:alpine
    volumes:
      - ..:/var/www/app
      - ./files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: fpm.Dockerfile
    environment:
      - GITHUB_USER_NAME=${GITHUB_USER_NAME}
      - GITHUB_USER_EMAIL=${GITHUB_USER_EMAIL}
    image: s4-cicd
    volumes:
      - ..:/var/www/app
