version: '3.7'
services:
  web:
    image: nginx:alpine
    container_name: cicd-web-1
    volumes:
      - ..:/var/www/app
      - ./files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web_net
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: fpm.dev.Dockerfile
    environment:
      - GITHUB_USER_NAME=${GITHUB_USER_NAME}
      - GITHUB_USER_EMAIL=${GITHUB_USER_EMAIL}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}?serverVersion=5.7
    image: jianzhong/cicd_fpm
    container_name: cicd-php-1
    volumes:
      - ..:/var/www/app
    networks:
      - web_net
      - data_net

  db:
    image: mariadb
    container_name: cicd-db-1
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - data_net

volumes:
  db_volume:

networks:
  web_net:
  data_net:
  