version: '3.7'
services:
  web:
    image: nginx:alpine
    volumes:
      - ..:/var/www/app
      - ./files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web_net
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: fpm.Dockerfile
    environment:
      - GITHUB_USER_NAME=${GITHUB_USER_NAME}
      - GITHUB_USER_EMAIL=${GITHUB_USER_EMAIL}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}?serverVersion=5.7
    image: jianzhong/cicd_fpm
    volumes:
      - ..:/var/www/app
    networks:
      - web_net
      - data_net
networks:
  web_net:
  data_net: